

server:
  error:
    include-message: always
  port: 9001
spring:
  datasource:
    password: admin123
    url: jdbc:postgresql://localhost:5433/MS
    username: adempiere
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: DEPARTMENT-SERVICE

